sudo: required
language: cpp

matrix:
  include:
  
  # linux configurationm  

    - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
       - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

  # Mac OS configuration

    -os: osx
    osx_image: xcode8
    compiler: gcc
    env:
      - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

  # Windows OS configuration

before_install:
  - eval "${MATRIX_EVAL}"
install:
  misc/travis/install.sh
script:
  echo
  echo "Success"
  echo